// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaktpbvfaoqnlzzxuhdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVha3RwYnZmYW9xbmx6enh1aGRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNzcxMTUsImV4cCI6MjA1NTY1MzExNX0.qsqV9hXYSF-ImTmQRmnqAstnO9asBzgYXlvToPiNgng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);